// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func InitializeRawRecordsRepository(collection string, db *mongo.Database) RawRecordsRepository {
	bsonService := NewBsonService()
	mongodbRawRecordsRepository := NewMongodbRawRecordsRepository(db, collection, bsonService)
	return mongodbRawRecordsRepository
}

func InitializeNationalHolidaysRepository(collection string, db *mongo.Database) NationalHolidaysRepository {
	bsonService := NewBsonService()
	mongoNationalHolidaysRepository := NewMongoNationalHolidaysRepository(db, collection, bsonService)
	return mongoNationalHolidaysRepository
}
