// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	lfucache "github.com/NdoleStudio/lfu-cache"
	"github.com/labstack/gommon/log"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func InitializeRawRecordsRepository(collection string, db *mongo.Database) RawRecordsRepository {
	bsonService := NewBsonService()
	mongodbRawRecordsRepository := NewMongodbRawRecordsRepository(db, collection, bsonService)
	return mongodbRawRecordsRepository
}

func InitializeNationalHolidaysRepository(collection string, db *mongo.Database) NationalHolidaysRepository {
	bsonService := NewBsonService()
	mongoNationalHolidaysRepository := NewMongoNationalHolidaysRepository(db, collection, bsonService)
	return mongoNationalHolidaysRepository
}

func InitializeEnrichedRecordsRepository(collection string, db *mongo.Database) EnrichedRecordsRepository {
	bsonService := NewBsonService()
	mongoNSEnrichedRecordsRepository := NewMongoNSEnrichedRecordsRepository(db, collection, bsonService)
	return mongoNSEnrichedRecordsRepository
}

// wire.go:

func InitializeCache(size int) LFUCache {
	cache, err := lfucache.New(size)
	if err != nil {
		log.Fatalf(err.Error())
	}
	return cache
}
