// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CancelTokenInput struct {
	Token string `json:"token"`
}

type Login struct {
	Email      string `json:"email"`
	Password   string `json:"password"`
	RememberMe bool   `json:"rememberMe"`
	ReCaptcha  string `json:"reCaptcha"`
}

type NewUser struct {
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Email     string `json:"email"`
	Password  string `json:"password"`
	ReCaptcha string `json:"reCaptcha"`
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type User struct {
	ID        string `json:"id"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Email     string `json:"email"`
}
